Changed the way URL’s is being used in our shell plugin
BenjaminMedia/wa-external-shell-v2 pull request #11
Opened 2017-03-14 14:31 UTC by sulfo

View changes with this URL: https://github.com/BenjaminMedia/wa-external-shell-v2/compare/development...feature-new-url-builder?w=1

2017-03-15 10:10 UTC, Xayer requested changes

2017-03-15 10:10 UTC, Xayer commented on admin/class-wa-external-header-v2-admin.php
> +    private function build_settings_info() {
@sulfo er stadig ikke enig i at det field er hardcoded. Så skal du nok gøre som de andre felter gør det.

```
private function build_settings_info($info_message) {
       return "<p>$info_message</p>";
}

2017-03-15 10:10 UTC, Xayer commented on admin/class-wa-external-header-v2-admin.php
> +        return '<input type="text" name="' . $this->options_group_name . '['. $option_key .']" value="' . $value . '" size="90">';
jeg er ikke helt sikker på at size parameteren er det du leder efter her.

Jeg tror at width ville kunne klarer det fint, ellers prøv at se om `.regular-text` klassen ikke kan gøre underværker 😜

2017-03-15 10:10 UTC, Xayer commented on public/class-wa-external-header-v2-public.php
> +    private $afubar;
@sulfo but why?? Hvis de allerede er defineret, er det vel fint... Eller hvad?

2017-03-15 10:10 UTC, Xayer commented on public/class-wa-external-header-v2-public.php
> +        if($hideShell) {
@sulfo wasn't me ¯\_(ツ)_/¯

2017-03-15 12:23 UTC, sulfo commented on public/class-wa-external-header-v2-public.php
> +    private $afubar;
Skal være opdelt ifg. PSR-2: http://www.php-fig.org/psr/psr-2/

`There MUST NOT be more than one property declared per statement.`

2017-03-15 14:49 UTC, sulfo commented on admin/class-wa-external-header-v2-admin.php
> +    private function build_settings_info() {
Jeg tvivler på det vil blive brugt, men kan godt lave den om til variabelt indhold.

2017-03-15 15:11 UTC, Xayer commented on admin/class-wa-external-header-v2-admin.php
> +    private function build_settings_info() {
@sulfo yes pls

2017-03-15 15:12 UTC, Xayer commented on public/class-wa-external-header-v2-public.php
> +    private $afubar;
@sulfo alright, my bad ¯\_(ツ)_/¯

2017-03-15 16:00 UTC, sulfo commented on admin/class-wa-external-header-v2-admin.php
> +        return '<input type="text" name="' . $this->options_group_name . '['. $option_key .']" value="' . $value . '" size="90">';
Smider en large på.

2017-03-15 16:01 UTC, sulfo commented
@Xayer Tag et kig igen

2017-03-16 11:27 UTC, Xayer approved these changes

2017-04-18 12:00 UTC, merged